# Generated by Django 3.1.2 on 2020-10-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_db_submitmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_submitmodel',
            old_name='letter_db',
            new_name='word_db',
        ),
    ]
